// 2. HARDCODED FALLBACK DATA (used when Firestore and cache are unavailable)
export const FALLBACK_CHARACTERS = [
    {
        id: "nanally",
        name: "Nanally (Наналлі)",
        rarity: 5,
        attribute: "Anima",
        role: "Main DPS",
        tier: "S+",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/4/44/Nanally_-_Character_Showcase.jpg/revision/latest/scale-to-width-down/200?cb=20241229191211",
        summary: "Найсильніший ДПС персонаж стихії Anima. Володіє неймовірною мобільністю завдяки антигравітаційним механікам та завдає колосальної шкоди авто-атаками супроводу.",
        weapon: "Goodnight Kiss (Сигнатурний Arc)",
        weaponF2p: "Raging Flames (Лють Полум'я)",
        cartridge: "Fireflies and the Forest (4-piece)",
        stats: ["Crit Rate (75%+)", "Crit DMG", "Anima DMG", "ATK%"],
        teamSynergy: "Zero (Космос), Sakiri (Закляття), Jiuyuan (Аніма)",
        lore: "Загадкова дівчина з лисячими вушками, яка обожнює грати з гравітацією. Працює незалежним детективом аномалій у Hethereau."
    },
    {
        id: "sakiri",
        name: "Sakiri (Сакірі)",
        rarity: 5,
        attribute: "Incantation",
        role: "Support",
        tier: "S+",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/3/32/Sakiri_Card.png/revision/latest/scale-to-width-down/200?cb=20260309141104",
        summary: "Найкращий саппорт у грі. Стягує ворогів, накладає потужне зниження опору до стихій та баффає силу атаки всієї команди після активації вибуху стихій.",
        weapon: "Good Boy's Grand Adventure (Сигнатурний)",
        weaponF2p: "Failing You, Heavy in My Heart",
        cartridge: "Speedy Hedgehog (4-piece)",
        stats: ["Cycle Intensity", "Break Effect", "Energy Charge Efficiency", "ATK%"],
        teamSynergy: "Nanally (Аніма), Zero (Космос), Daffodil (Хаос)",
        lore: "Весела та енергійна дівчина, яка завжди носить із собою іграшкового кролика. Здатна бачити приховані нитки долі за допомогою заклять."
    },
    {
        id: "jiuyuan",
        name: "Jiuyuan (Цзююань)",
        rarity: 5,
        attribute: "Anima",
        role: "Sub-DPS",
        tier: "S",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/5/57/Jiuyuan_Card.png/revision/latest/scale-to-width-down/200?cb=20260309140453",
        summary: "Потужний суб-ДПС, який наносить швидку вибухову шкоду. Ідеально підходить для активації реакції Blossom (Цвітіння) разом з Наналлі.",
        weapon: "Jade Dragon Whisper (Сигнатурний)",
        weaponF2p: "Rising Wind (Порив Вітру)",
        cartridge: "Fireflies and the Forest (4-piece)",
        stats: ["Crit Rate", "Crit DMG", "Anima DMG", "Energy Charge Efficiency"],
        teamSynergy: "Nanally (Аніма), Sakiri (Закляття), Zero (Космос)",
        lore: "Мисливиця на аномалії стародавнього роду з витонченими манерами. Використовує віяло для виклику аномальних повітряних потоків."
    },
    {
        id: "hotori",
        name: "Hotori (Хоторі)",
        rarity: 5,
        attribute: "Cosmos",
        role: "Sub-DPS",
        tier: "S",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/4/41/Hotori_in_game_Model.png/revision/latest/scale-to-width-down/200?cb=20260223173459",
        summary: "Унікальний саппорт/саб-ДПС, здатний записувати та повторювати навички активних членів загону, подвоюючи загальну шкоду команди.",
        weapon: "Echoes of Eternity",
        weaponF2p: "Appraiser's Notebook",
        cartridge: "Speedy Hedgehog (4-piece)",
        stats: ["Energy Charge Efficiency", "Cycle Intensity", "ATK%", "HP%"],
        teamSynergy: "Nanally (Аніма), Adler (Хаос), Haniel (Закляття)",
        lore: "Тихий оцінювач аномальних предметів, який проводить більшу частину часу в бібліотеці антикварної крамниці Eibon."
    },
    {
        id: "zero",
        name: "Zero (Зеро)",
        rarity: 5,
        attribute: "Cosmos",
        role: "Support",
        tier: "S",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/c/c2/Esper_Zero_Male_Card.png/revision/latest/scale-to-width-down/200?cb=20260315121329",
        summary: "Головний герой. Володіє Cosmos атрибутом, що є універсальним каталізатором для активації ефекту Esper Cycle для будь-якої іншої стихії.",
        weapon: "Eibon Legacy (Спадщина Ейбона)",
        weaponF2p: "Hunter's Resolve (Рішучість Мисливця)",
        cartridge: "Speedy Hedgehog (4-piece)",
        stats: ["ATK%", "Crit Rate", "Cycle Intensity", "Energy Charge Efficiency"],
        teamSynergy: "Будь-який ДПС персонаж стихії Anima або Incantation",
        lore: "Новий володар антикварної крамниці Eibon, що втратив спогади про своє минуле, але володіє дивним даром бачити сутність аномалій."
    },
    {
        id: "adler",
        name: "Adler (Адлер)",
        rarity: 4,
        attribute: "Incantation",
        role: "Support",
        tier: "A",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/3/33/Adler_Card.png/revision/latest/scale-to-width-down/200?cb=20260309120100",
        summary: "Надійний щитовик стихії Incantation. Створює міцний щит, міцність якого масштабується від його захисту (DEF), та допомагає збивати стійкість ворогів.",
        weapon: "Sentinel's Barrier",
        weaponF2p: "Rusty Alloy Shield",
        cartridge: "Speedy Hedgehog (4-piece) або Guard Set",
        stats: ["DEF%", "Flat DEF", "Break Effect", "Energy Charge Efficiency"],
        teamSynergy: "Nanally (Аніма), Sakiri (Закляття), Zero (Космос)",
        lore: "Колишній охоронець, який тепер допомагає крамниці Eibon із важкими замовленнями у небезпечних зонах Hethereau."
    },
    {
        id: "mint",
        name: "Mint (Мінт)",
        rarity: 4,
        attribute: "Anima",
        role: "Main DPS",
        tier: "A",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/2/20/Mint_Card.png/revision/latest/scale-to-width-down/200?cb=20260307142424",
        summary: "Хороший безкоштовний F2P ДПС персонаж. Проста механіка комбо-атак та швидка перезарядка елементальних умінь.",
        weapon: "Zephyr Blade",
        weaponF2p: "Steel Rapier",
        cartridge: "Fireflies and the Forest (4-piece)",
        stats: ["ATK%", "Crit Rate", "Crit DMG", "Anima DMG"],
        teamSynergy: "Zero (Космос), Haniel (Закляття), Adler (Хаос)",
        lore: "Молода стажерка в Eibon, яка прагне стати найкращим оцінювачем аномалій у місті."
    },
    {
        id: "haniel",
        name: "Haniel (Ханіель)",
        rarity: 4,
        attribute: "Psyche",
        role: "Support",
        tier: "A",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/b/b9/Haniel_Card.png/revision/latest/scale-to-width-down/200?cb=20260309131027",
        summary: "Потужний саппорт стихії Psyche. Баффає силу атаки загону та викликає помічника Hootie, який допомагає наносити шкоду та підтримувати союзників.",
        weapon: "Mind Royale (Рояль Розуму)",
        weaponF2p: "Ready-Ready (Реді-Реді)",
        cartridge: "Tiny Big Adventure (4-piece)",
        stats: ["ATK%", "Crit Rate", "Psyche DMG", "Energy Charge Efficiency"],
        teamSynergy: "Mint (Аніма), Zero (Космос), Adler (Закляття)",
        lore: "Турботлива та мила дівчина, яка завжди носить із собою іграшкового сову-помічника Hootie, здатного надихати союзників під час бою."
    },
    {
        id: "lacrimosa",
        name: "Lacrimosa (Лакрімоза)",
        rarity: 5,
        attribute: "Chaos",
        role: "Main DPS",
        tier: "S",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/3/37/Lacrimosa_-_Character_Showcase.jpg/revision/latest/scale-to-width-down/200?cb=20241229191213",
        summary: "Новий анонсований персонаж версії 1.1. Спеціалізується на Chaos шкоді та потужних комбо-атаках масками.",
        weapon: "Tragedy & Comedy (Сигнатурний)",
        weaponF2p: "Failing You, Heavy in My Heart",
        cartridge: "Chaos Eclipse (4-piece)",
        stats: ["Crit Rate", "Crit DMG", "Chaos DMG", "ATK%"],
        teamSynergy: "Sakiri (Закляття), Zero (Космос), Hotori (Космос)",
        lore: "Театральна акторка, чиї вистави зачаровують глядачів Гетеро. Кажуть, що її маски мають власне аномальне життя."
    },
    {
        id: "daffodil",
        name: "Daffodil (Даффоділ)",
        rarity: 5,
        attribute: "Chaos",
        role: "Sub-DPS",
        tier: "S",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/a/af/Daffodill_Card.png/revision/latest/scale-to-width-down/200?cb=20260309135850",
        summary: "Потужний Burst DPS стихії Chaos, що спеціалізується на пробитті щитів (Break). Накопичує силу поза полем бою і завдає величезної вибухової шкоди при перемиканні.",
        weapon: "Youthful Fantasy (Сигнатурний Arc)",
        weaponF2p: "Shiny Days (Світлі Дні)",
        cartridge: "Chaos Eclipse (4-piece)",
        stats: ["Break Intensity", "Crit Rate", "Crit DMG", "ATK%"],
        teamSynergy: "Nanally (Аніма), Zero (Космос), Sakiri (Закляття)",
        lore: "Мовчазна та загадкова охоронниця антикварної крамниці Eibon. Володіє калейдоскопічними очима і приховує під холодною маскою відданість друзям."
    },
    {
        id: "baicang",
        name: "Baicang (Байцан)",
        rarity: 5,
        attribute: "Incantation",
        role: "Main DPS",
        tier: "S",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/5/5c/Baicang_Card.png",
        summary: "Потужний Main DPS стихії Incantation. Використовує механіку витрати власного здоров'я для підвищення шкоди. Потребує надійного цілителя в команді.",
        weapon: "Camellia Society (Товариство Камелій)",
        weaponF2p: "A Time Will Come (Час прийде)",
        cartridge: "Crimson: Twin Butterflies (4-piece)",
        stats: ["Crit Rate", "Crit DMG", "Incantation DMG", "ATK%"],
        teamSynergy: "Haniel (Закляття), Sakiri (Закляття), Adler (Хаос)",
        lore: "Капітан підрозділу ETD-4 Бюро контролю аномалій. Досвідчений ветеран з невимушеним характером, який піклується про своїх підлеглих як старший брат."
    },
    {
        id: "chiz",
        name: "Chiz (Чіз)",
        rarity: 5,
        attribute: "Cosmos",
        role: "Main DPS",
        tier: "S",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/2/21/Chiz_Card.png",
        summary: "Потужний Main DPS стихії Cosmos. Її ультимейт ігнорує велику частину захисту ворога, а сигнатурна зброя дає додаткову шкоду залежно від ваших Fons (монет).",
        weapon: "Contemplative Cat (Замислений Кот)",
        weaponF2p: "Wild Reverie (Дика мрія)",
        cartridge: "Lost Radiance (4-piece)",
        stats: ["Crit Rate", "Crit DMG", "Cosmos DMG", "ATK%"],
        teamSynergy: "Zero (Космос), Sakiri (Закляття), Hotori (Космос)",
        lore: "Персонаж, пов'язаний із Безіменним Банком. Має ділову жилку та користується важким молотом-йокай для вибивання боргів та аномалій."
    },
    {
        id: "fadia",
        name: "Fadia (Фадія)",
        rarity: 5,
        attribute: "Psyche",
        role: "Support",
        tier: "A",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/6/68/Fadia_Card.png",
        summary: "Потужний Sustain-персонаж стихії Psyche. Працює як танк-цілитель, що перенаправляє шкоду союзників на себе та відновлює здоров'я в режимі Lilith.",
        weapon: "Eternal Waltz (Вічний вальс)",
        weaponF2p: "Medic's Flask (Флакон медика)",
        cartridge: "Tiny Big Adventure (4-piece)",
        stats: ["HP%", "Flat HP", "Psyche DMG", "Energy Charge Efficiency"],
        teamSynergy: "Baicang (Закляття), Nanally (Аніма), Zero (Космос)",
        lore: "Дивовижна дівчина-вампір з Бюро контролю аномалій, яка носить із собою гігантський надгробок як щит та зброю."
    },
    {
        id: "hathor",
        name: "Hathor (Хатор)",
        rarity: 5,
        attribute: "Lakshana",
        role: "Sub-DPS",
        tier: "S",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/3/30/Hathor_Card.png",
        summary: "Потужний Burst Sub-DPS стихії Lakshana. Використовує механіку накопичення стаків Express Delivery Power для завдання величезної вибухової шкоди.",
        weapon: "Raging Flames (Лють Полум'я)",
        weaponF2p: "Sentinel's Barrier (Бар'єр Вартового)",
        cartridge: "Street Boxer (4-piece)",
        stats: ["Crit Rate", "Crit DMG", "Lakshana DMG", "ATK%"],
        teamSynergy: "Zero (Космос), Sakiri (Закляття), Daffodil (Хаос)",
        lore: "Впливова дівчина-фіксер з елітних кіл Гетеро, яка тісно співпрацює зі Sterry Express. Її витонченість приховує неперевершені бойові вміння."
    },
    {
        id: "aurelia",
        name: "Aurelia (Аурелія)",
        rarity: 4,
        attribute: "Psyche",
        role: "Main DPS",
        tier: "B",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/f/fd/Aurelia_-_Character_Promo.png",
        summary: "A-Rank Main DPS стихії Psyche. Використовує атаки медуз у стані Cadenza для нанесення значної шкоди. Отримується безкоштовно за 3-денний вхід.",
        weapon: "Stellar Veil (Зоряна Вуаль)",
        weaponF2p: "Oraora! (Ораора!)",
        cartridge: "Devil's Blood: Curse (4-piece)",
        stats: ["Crit Rate", "Crit DMG", "Psyche DMG", "ATK%"],
        teamSynergy: "Zero (Космос), Fadia (Психея), Sakiri (Закляття)",
        lore: "Студентка-музикант у Гетеро, яка виявила в собі аномальні здібності під час одного з вуличних виступів. Керує аномальними медузами."
    },
    {
        id: "edgar",
        name: "Edgar (Едгар)",
        rarity: 4,
        attribute: "Cosmos",
        role: "Support",
        tier: "B",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/1/1d/Edgar_Card.png",
        summary: "Доступний цілитель стихії Cosmos. Його навички відновлюють здоров'я союзникам пропорційно його максимальному HP, а ультимейт створює велику зону лікування.",
        weapon: "Call of the Twisted City (Заклик викривленого міста)",
        weaponF2p: "Mind Royale (Рояль Розуму)",
        cartridge: "Thea's Night Tavern (4-piece)",
        stats: ["HP%", "Healing Bonus", "Flat HP", "Energy Charge Efficiency"],
        teamSynergy: "Zero (Космос), Hotori (Космос), Jiuyuan (Аніма)",
        lore: "Співробітник антикварної крамниці Eibon. Спокійний та врівноважений юнак, який завжди готовий надати першу допомогу та смачний гарячий чай."
    },
    {
        id: "skia",
        name: "Skia (Скіа)",
        rarity: 4,
        attribute: "Lakshana",
        role: "Sub-DPS",
        tier: "B",
        avatar: "https://static.wikia.nocookie.net/neverness-to-everness/images/0/01/Skia_by_nte_1.jpg/revision/latest/scale-to-width-down/1200?cb=20260212004246",
        summary: "Потужний суб-ДПС стихії Lakshana, який спеціалізується на мітках Fang Thrust та унікальних навичках прихованості в тіні. Чудово доповнює команди на реакції Remora.",
        weapon: "Watch Your Heads! (Стережись голів!)",
        weaponF2p: "Good Boy's Grand Adventure (Велика пригода хорошого хлопчика)",
        cartridge: "Street Boxer (4-piece)",
        stats: ["Crit Rate", "Crit DMG", "Lakshana DMG", "ATK%"],
        teamSynergy: "Zero (Космос), Sakiri (Закляття), Nanally (Аніма)",
        lore: "Лейтенант підрозділу ETD-4 Бюро контролю аномалій. Мовчазний вовк-офіцер із великим шрамом на лівому оці, який вірно несе службу."
    }
];

export const FALLBACK_PROMO_CODES = [
    { code: "NTE429vtuber", rewards: "30,000 Beetle Coins, 30,000 Fons", active: true },
    { code: "NTEWINFONS", rewards: "10,000 Fons", active: true },
    { code: "NTEFUNGAME", rewards: "10,000 Fons", active: true },
    { code: "NTENENE", rewards: "10,000 Clicky Fries, 10 DynamiK", active: true },
    { code: "NTEFREE", rewards: "30,000 Fons", active: true },
    { code: "NTEvtuber200", rewards: "10,000 Beetle Coins, 10,000 Fons", active: true },
    { code: "NTEGIFT", rewards: "50 Annulith, 5 Rising Hunter Guides, 5 Light Dye", active: true },
    { code: "504980102FKGOVNS", rewards: "30 Annulith, 1 Gubichi Flavor Chips, 20,000 Beetle Coins", active: true }
];

export const FALLBACK_TIMELINE_EVENTS = [
    {
        date: "29 Квітня 2026",
        title: "Глобальний Реліз Neverness to Everness (1.0)",
        desc: "Офіційний запуск гри на PC, iOS та Android. Доступні початкові розділи сюжету в місті Гетеро, лімітований банер Наналлі, а також стартові події.",
        status: "Released",
        badgeClass: "badge-anima"
    },
    {
        date: "23 Травня 2026",
        title: "Стрім Розробників: Презентація Версії 1.1",
        desc: "Спеціальна трансляція від Hotta Studio. Анонсовано нових персонажів Lacrimosa (Хаос ДПС), нові локації міста, ігрові режими та промокоди.",
        status: "Released",
        badgeClass: "badge-incant"
    },
    {
        date: "3-4 Червня 2026",
        title: "Оновлення 1.1: 'Lacrimosa of Chaos'",
        desc: "Вихід першого великого патчу. Старт першої фази банера з Лакрімозою. Новий сюжетний епізод 'Театр Тіней'. Початок літнього івенту.",
        status: "Upcoming",
        badgeClass: "badge-chaos"
    },
    {
        date: "Липень 2026 (Прогноз)",
        title: "Оновлення 1.2 та нові герої Shinku й Iroi",
        desc: "Очікуване оновлення на основі витоків інформації. Додавання нових аномальних зон на півночі Гетеро та вихід нових персонажів S-рангу.",
        status: "Upcoming",
        badgeClass: "badge-phase"
    }
];
